Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  #config.vm.network "forwarded_port", guest: 80, host: 8086
  config.vm.network "private_network", ip: "10.0.0.11", auto_config: false
  ####### Provision #######
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "../playbook.yml"
    ansible.verbose = true
  end
end
